image: docker:latest
services:
    - docker:dind

stages:
  - build
  - deploy

build_image:
  stage: build
  script:
    - docker build -f Dockerfile --iidfile imageid.txt -t gitlab-docker-heroku:v$CI_PIPELINE_ID .
    - docker save gitlab-docker-heroku:v$CI_PIPELINE_ID > app.tar
  artifacts:
    paths:
      - imageid.txt
      - app.tar

deploy_gitlab:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker load -i app.tar
    - docker tag gitlab-docker-heroku:v$CI_PIPELINE_ID registry.gitlab.com/patricksferraz/gitlab-docker-heroku:v$CI_PIPELINE_ID
    - docker push registry.gitlab.com/patricksferraz/gitlab-docker-heroku:v$CI_PIPELINE_ID

deploy_heroku_develop:
  stage: deploy
  variables:
    HEROKU_API_KEY: $HEROKU_DEVELOP_API_KEY
  script:
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
    - docker load -i app.tar
    - docker tag gitlab-docker-heroku:v$CI_PIPELINE_ID registry.heroku.com/dev-gitlab-docker-heroku:v$CI_PIPELINE_ID
    - docker push registry.heroku.com/dev-gitlab-docker-heroku:v$CI_PIPELINE_ID
    - apk add --no-cache curl
    - echo "Docker Image ID is $(cat imageid.txt)"
    - |-
      curl -X PATCH https://api.heroku.com/apps/dev-gitlab-docker-heroku/formation --header "Content-Type: application/json" --header "Accept: application/vnd.heroku+json; version=3.docker-releases" --header "Authorization: Bearer ${HEROKU_API_KEY}" --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat imageid.txt)'" } ] }'
  only:
    - develop

deploy_heroku_staging:
  stage: deploy
  variables:
    HEROKU_API_KEY: $HEROKU_STAGING_API_KEY
  script:
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
    - docker load -i app.tar
    - docker tag gitlab-docker-heroku:v$CI_PIPELINE_ID registry.heroku.com/stg-gitlab-docker-heroku:v$CI_PIPELINE_ID
    - docker push registry.heroku.com/stg-gitlab-docker-heroku:v$CI_PIPELINE_ID
    - apk add --no-cache curl
    - echo "Docker Image ID is $(cat imageid.txt)"
    - |-
      curl -X PATCH https://api.heroku.com/apps/stg-gitlab-docker-heroku/formation --header "Content-Type: application/json" --header "Accept: application/vnd.heroku+json; version=3.docker-releases" --header "Authorization: Bearer ${HEROKU_API_KEY}" --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat imageid.txt)'" } ] }'
  only:
    - staging

deploy_heroku_production:
  stage: deploy
  variables:
    HEROKU_API_KEY: $HEROKU_PRODUCTION_API_KEY
  script:
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
    - docker load -i app.tar
    - docker tag gitlab-docker-heroku:v$CI_PIPELINE_ID registry.heroku.com/gitlab-docker-heroku:v$CI_PIPELINE_ID
    - docker push registry.heroku.com/gitlab-docker-heroku:v$CI_PIPELINE_ID
    - apk add --no-cache curl
    - echo "Docker Image ID is $(cat imageid.txt)"
    - |-
      curl -X PATCH https://api.heroku.com/apps/gitlab-docker-heroku/formation --header "Content-Type: application/json" --header "Accept: application/vnd.heroku+json; version=3.docker-releases" --header "Authorization: Bearer ${HEROKU_API_KEY}" --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat imageid.txt)'" } ] }'
  only:
    - master